server:
  port: 8160 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: guli-sms # 服务名
#spring:
  redis:
    host: 192.168.56.101


eureka:
  client:
    service-url:
      defaultZone: http://localhost:9110/eureka/
  instance:
    prefer-ip-address: true
    # 心跳检测检测与续约时间
    # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
    # 配置说明
    # lease-renewal-interval-in-seconds 每间隔5s，向服务端发送一次心跳，证明自己依然”存活“，默认 30
    lease-renewal-interval-in-seconds: 5
    # lease-expiration-duration-in-seconds  告诉服务端，如果我10s之内没有给你发心跳，就代表我“死”了，将我踢出掉，默认 90
    lease-expiration-duration-in-seconds: 10

#阿里云短信
aliyun:
  sms:
    regionid: cn-hangzhou
    keyid: LTAI4FcTkSfbd3ZP1yMUExhK
    keysecret: sujnBQGJLJjJs5sLHqJVwEz5OawSSz
    templatecode: SMS_182541170
    signname: 谷粒商城